version: "3.8"

services:
  web:
    build: ./wikiweaver-web
    ports:
      - 443:443
    volumes:
      - ./secrets:/secrets

  server:
    build: ./wikiweaver-server
    ports:
      - 4242:4242
    volumes:
      - ./secrets:/secrets
