version: "3.8"

services:
  web:
    build: ./wikiweaver-web
    ports:
      - 4243:443
    volumes:
      - /etc/letsencrypt/live/stuffontheinter.net/fullchain.pem:/fullchain.pem
      - /etc/letsencrypt/live/stuffontheinter.net/privkey.pem:/privkey.pem

  server:
    build: ./wikiweaver-server
    ports:
      - 4242:4242
    volumes:
      - /etc/letsencrypt/live/stuffontheinter.net/fullchain.pem:/fullchain.pem
      - /etc/letsencrypt/live/stuffontheinter.net/privkey.pem:/privkey.pem
